- name: coping prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: coping alert configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: stating prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: coping alertmanager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: stating alertmanager service
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: yes