- name: Downloading node-exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Downloading node-exporter service
  ansible.builtin.template:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service --collector.systemd

- name: Starting Node-Exporter service
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
    enabled: yes
    daemon-reload: yes