groups:
  - name: Infra_alerts
    rules:
      - alert: ServerDownAlerts
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Server Down Alert